FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

COPY docker/source.list.d/ubuntu.sources /etc/apt/sources.list.d/ubuntu.sources
RUN apt-get update

# install build tools
RUN apt-get install -y sudo curl wget iputils-ping pkg-config
RUN apt-get install -y g++ gdb cmake make git lcov

# install python
RUN apt-get install -y python3 python3-pip
RUN rm /usr/lib/python3.12/EXTERNALLY-MANAGED # install globally

# install conan and test tools
RUN pip install conan gcovr pytest pytest-html requests

# download musl toolchain
RUN wget https://musl.cc/aarch64-linux-musl-cross.tgz && tar xzvf /aarch64-linux-musl-cross.tgz && rm /aarch64-linux-musl-cross.tgz

USER ubuntu
WORKDIR /home/ubuntu/

COPY --chown=ubuntu docker/conan/global.conf global.conf
RUN conan config install global.conf

COPY --chown=ubuntu docker/conan/profile_build.txt .conan2/profiles/default
COPY --chown=ubuntu docker/conan/profile_host_armv8.txt profile_host_armv8.txt
COPY --chown=ubuntu docker/conan/profile_host_x86_64.txt profile_host_x86_64.txt

COPY --chown=ubuntu conandata.yml conandata.yml
COPY --chown=ubuntu conanfile.py conanfile.py

RUN conan install --build=missing --profile:host=profile_host_x86_64.txt \
    && conan cache clean --source --build --download --temp

RUN conan install --build=missing --profile:host=profile_host_armv8.txt \
    && conan cache clean --source --build --download --temp

RUN conan install --build=missing --profile:host=profile_host_x86_64.txt \
    --settings:host="build_type=Debug" \
    && conan cache clean --source --build --download --temp

