#!/bin/bash
set -e
echo "dbus2http postinst..."

USER_NAME="dbus2http"
SRV_NAME="dbus2http"

if ! id -u "${USER_NAME}" >/dev/null 2>&1; then
    echo "Creating user ${USER_NAME} for ${SRV_NAME}..." >&2
    useradd -r -s "${USER_SHELL}" -M -U -c "User of service ${SRV_NAME}" "${USER_NAME}"
fi

chown ${USER_NAME}:${USER_NAME} /opt/cosmos/lib/systemd/system/${SRV_NAME}.service
chown ${USER_NAME}:${USER_NAME} /opt/cosmos/etc/dbus-1/system.d/com.syriusrobotics.${SRV_NAME}.conf
chown ${USER_NAME}:${USER_NAME} /opt/cosmos/bin/${SRV_NAME}

chmod 644 /opt/cosmos/etc/dbus-1/system.d/com.syriusrobotics.${SRV_NAME}.conf
chmod 644 /opt/cosmos/etc/dbus-1/system.d/com.syriusrobotics.${SRV_NAME}.conf
chmod 750 /opt/cosmos/bin/${SRV_NAME}

systemctl enable --now /opt/cosmos/lib/systemd/system/${SRV_NAME}.service

sync
