cmake_minimum_required(VERSION 3.10)


function(pack_deb CONTACT VENDOR COMPONENT)

  set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
  set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
  set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})
  if (NOT BUILD_NUMBER)
    set(BUILD_NUMBER "PATCH")
  endif()
  set(CPACK_DEBIAN_PACKAGE_VERSION ${PROJECT_VERSION}.${BUILD_NUMBER})
  set(CPACK_SYSTEM_NAME "Linux")
  if (CMAKE_CROSSCOMPILING)
    set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "arm64")
  else()
    set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")
  endif()
  set(CPACK_PACKAGE_FILE_NAME ${CMAKE_PROJECT_NAME}_${CPACK_DEBIAN_PACKAGE_VERSION}-${CPACK_SYSTEM_NAME}_${CPACK_DEBIAN_PACKAGE_ARCHITECTURE})

  set(CPACK_PACKAGE_CONTACT ${CONTACT})
  set(CPACK_PACKAGE_VENDOR ${VENDOR})

  set(CPACK_DEBIAN_PACKAGE_SECTION "misc")
  set(CPACK_DEBIAN_PACKAGE_PRIORITY "extra")
  set(CPACK_INSTALL_CMAKE_PROJECTS "${CMAKE_BINARY_DIR};${CMAKE_PROJECT_NAME};${COMPONENT};/")
  set(CPACK_PACKAGING_INSTALL_PREFIX "/")
  set(CPACK_OUTPUT_CONFIG_FILE "${CMAKE_PROJECT_NAME}CPackConfig.cmake")
  set(CPACK_GENERATOR "DEB")

  set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY FALSE)
  set(CPACK_MONOLITHIC_INSTALL TRUE)
  set(CPACK_VERBATIM_VARIABLES TRUE)

  # control extra files
  set(_CONTROL_EXTRA_LIST)
  list(APPEND _CONTROL_EXTRA_LIST ${CMAKE_CURRENT_SOURCE_DIR}/debian/preinst)
  list(APPEND _CONTROL_EXTRA_LIST ${CMAKE_CURRENT_SOURCE_DIR}/debian/postinst)
  list(APPEND _CONTROL_EXTRA_LIST ${CMAKE_CURRENT_SOURCE_DIR}/debian/prerm)
  list(APPEND _CONTROL_EXTRA_LIST ${CMAKE_CURRENT_SOURCE_DIR}/debian/postrm)
  set(CPACK_DEBIAN_PACKAGE_CONTROL_STRICT_PERMISSION TRUE)
  set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA ${_CONTROL_EXTRA_LIST})

  include(CMakePrintHelpers)
  cmake_print_variables(CPACK_DEBIAN_PACKAGE_VERSION)
  cmake_print_variables(CPACK_SYSTEM_NAME)
  cmake_print_variables(CPACK_DEBIAN_PACKAGE_ARCHITECTURE)
  cmake_print_variables(CPACK_PACKAGE_FILE_NAME)
  cmake_print_variables(CPACK_PACKAGE_CONTACT)
  cmake_print_variables(CPACK_PACKAGE_VENDOR)
  cmake_print_variables(CPACK_INSTALL_CMAKE_PROJECTS)
  cmake_print_variables(CPACK_PACKAGING_INSTALL_PREFIX)
  cmake_print_variables(CPACK_OUTPUT_CONFIG_FILE)
  cmake_print_variables(CPACK_GENERATOR)
  cmake_print_variables(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA)

  include (CPack)

endfunction()
